---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: try-watch-pod-labels
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: try-watch-pod-labels
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - pods
    verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: try-watch-pod-labels
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: try-watch-pod-labels
subjects:
  - kind: ServiceAccount
    name: try-watch-pod-labels
---
apiVersion: v1
kind: Pod
metadata:
  name: try-watch-pod-labels
  labels:
    app: try-watch-pod-labels
spec:
  serviceAccountName: try-watch-pod-labels
  containers:
    - name: try-watch-pod-labels
      image: try-watch-pod-labels
  restartPolicy: Always
